spring.application.name=finpay-payment-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/finpay
spring.datasource.username=finpay
spring.datasource.password=finpay123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true